# this is make file
a.out:input.o sqlite_mem.o main.c
	gcc input.o sqlite_mem.o main.c -o a.out
input.o:input.c
	gcc -c input.c -o input.o
sqlite_mem.o:sqlite_mem.c
	gcc -c sqlite_mem.c -o sqlite_mem.o
